services:
  brain-batch-backend:
    container_name: brain-batch-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - brain-batch-net
  
  brain-batch-frontend:
    container_name: brain-batch-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - brain-batch-net
    depends_on:
      - brain-batch-backend

networks:
  brain-batch-net:
    driver: bridge
